### PR TITLE
http-job-refactor

### PR DESCRIPTION
**Pull request by kghamilton89**
* Refactor and update of `jobs/http.md`.
* New screenshots added.
* Legacy features removed.
* Links added where to needed.
* Style changes.

### CODE REVIEW

**Comment by kghamilton89** [comment]
@unrealwork if all changes are correct, please set **Done** label after you review.

**Comment by kghamilton89** [comment]
@unrealwork  please review once more.

There is an error in the **Metric Field** parameter tooltip. See attached:
https://imgur.com/a/860xGdV

**Comment by rodionos** [comment]
Mask our hosts on the screenshot, also display commands collected by the http job. The commands are visible when you click on Test.

**Comment by rodionos** [comment]
For an example of what we need - take a look at the SNMP job - it is fully and nicely documented: https://axibase.com/docs/axibase-collector/jobs/snmp.html

**Pull request merged**
