### PR TITLE
OID Reference table in jobs/snmp

### PR DESCRIPTION
**Pull request by kirmanak**

### CODE REVIEW

**Comment by kirmanak** [comment]
There are groups only for UCD-SNMP-MIB, IF-MIB is not done yet.

**Comment by rodionos** [comment]
Fix linter problems by backticking all object names.

**Comment by kirmanak** [comment]
@rodionos please review. `.dictionary` is sorted by `GNU sort 8.26` utility. UCD SNMP and IF MIBs are described.

**Comment by rodionos** [comment]
There are too many dictionary words that should not be in our dictionary, because it allows errors in other articles. We should either fix the words at the source or backtick them. For instance, instead of `timezone` use `time zone`.

**Comment by kirmanak** [comment]
@rodionos I've added only four words to the dictionary:  "reportable", "inodes", "loopback", "unicast". The source of  all other modifications is the sorting.
The source of strange numbers is my shell script, which parses MIB files. It uses sed to automatically backtick all numbers, but I didn't think about cases, when they separate parts of a number with commas for convenience.

**Pull request merged**
